export default function Head() {
    return (
      <>
        <title>About Page</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="Learn about this sweet Next 13 example app. This head component makes it easy to add metadata for any page!" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </>
    )
  }